name: flowr_root
channels:
  - conda-forge
  - mx
  - schrodinger
dependencies:
  - python=3.11
  - pip
  - notebook
  - matplotlib
  - xtb
  - vina
  - conda-forge::openmm
  - conda-forge::openff-toolkit
  - conda-forge::openmmforcefields
  # Moved DL frameworks to pip to avoid conda solver conflicts
  # - pytorch::pytorch>=2.0
  # - conda-forge::lightning=2.5.0
  - conda-forge::rdkit=2023.9.6
  - conda-forge::jupyter
  - conda-forge::openbabel
  - conda-forge::prody
  - conda-forge::pypdb
  - conda-forge::datamol
  - conda-forge::py3dmol
  - conda-forge::setuptools>=69.5
  - conda-forge::scipy
  - conda-forge::packaging<25.0
  - mx::reduce
  - conda-forge::biopython=1.81
  - conda-forge::mdanalysis=2.7.0
  - conda-forge::pdbfixer
  - conda-forge::nglview
  - pip:
      - torch
      - lightning
      - ase
      - lmdb
      - nglview
      - rmsd
      - torch_ema==0.3
      - tensorboard
      - xtb
      - datamol
      - prody
      - meeko
      - seaborn
      - tensorboard
      - tensorboardX
      - aim
      - hydride
      - plinder==0.2.5
      - biotite==1.0.1
      - numpy==1.26.2
      - pandas>=2.1.1
      - torchmetrics==1.6.1
      - prolif==2.0.3
      - openbabel-wheel==3.1.1.19
      - more-itertools
      - requests
      - timeout-decorator
      - typing_extensions
      - wandb
      - pdbinf
      - molvs
      - mlflow
      - biopandas
      - torchdata==0.8.0
      - submitit
      - fcd
      - useful_rdkit_utils
      - torch_geometric
      - docutils==0.17.1
      - tensordict==0.9.1
      - packaging
